apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-ui-sa
  namespace: fleet-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-ui-role
rules:
  - apiGroups: ["fleet.cattle.io"]
    resources: ["gitrepos", "bundles"]
    verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-ui-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-ui-role
subjects:
  - kind: ServiceAccount
    name: fleet-ui-sa
    namespace: fleet-ui
