apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-ui-sa
  namespace: fleet-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fleet-ui
  name: fleet-ui-role
rules:
  - apiGroups: ["fleet.cattle.io/v1alpha1"]
    resources: ["gitrepos", "bundles"]
    verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-ui-binding
  namespace: fleet-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-ui-role
subjects:
  - kind: ServiceAccount
    name: fleet-ui-sa
    namespace: fleet-ui
