apiVersion: v1
kind: Service
metadata:
  name: fleet-ui-svc
  namespace: fleet-ui
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: fleet-ui
