apiVersion: v1
kind: Service
metadata:
  name: fleet-ui-svc
  namespace: fleet-ui
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: fleet-ui
